=== Rawframe-Project/maul-locale/test/cldr/common/dtd/ldml.dtd
<!--
SPDX-License-Identifier: MIT
Copyright (c) 2026 Sirac Ozmen

A cut of CLDR's ldml.dtd for test_genresolve: the elements the fixture
files use, with CLDR's annotations on their attributes.
-->
<!ELEMENT ldml (identity, (alias | (localeDisplayNames?, layout?, dates?, numbers?, units?)))>
<!ATTLIST ldml draft (approved | contributed | provisional | unconfirmed | true | false) #IMPLIED >
    <!--@METADATA-->
<!ELEMENT alias EMPTY >
<!ATTLIST alias source NMTOKEN #REQUIRED >
<!ATTLIST alias path CDATA #IMPLIED >
<!ELEMENT identity (version, language, script?, territory?) >
<!ELEMENT version EMPTY >
<!ATTLIST version number CDATA #REQUIRED >
    <!--@METADATA-->
<!ELEMENT script EMPTY >
<!ATTLIST script type NMTOKEN #REQUIRED >
<!ELEMENT territory EMPTY >
<!ATTLIST territory type NMTOKEN #REQUIRED >
<!ELEMENT localeDisplayNames (languages?) >
<!ELEMENT languages (alias | language*) >
<!ELEMENT language ( #PCDATA ) >
<!ATTLIST language type NMTOKEN #REQUIRED >
<!ATTLIST language alt NMTOKENS #IMPLIED >
<!ATTLIST language menu NMTOKENS #IMPLIED >
<!ATTLIST language draft (approved | contributed | provisional | unconfirmed | true | false) #IMPLIED >
    <!--@METADATA-->
<!ELEMENT layout (orientation?) >
<!ELEMENT orientation EMPTY >
<!ATTLIST orientation characters (left-to-right | right-to-left | top-to-bottom | bottom-to-top) #IMPLIED >
    <!--@VALUE-->
<!ATTLIST orientation lines (left-to-right | right-to-left | top-to-bottom | bottom-to-top) #IMPLIED >
    <!--@VALUE-->
<!ELEMENT dates (calendars?) >
<!ELEMENT calendars (calendar*) >
<!ELEMENT calendar (alias | months?) >
<!ATTLIST calendar type NMTOKEN #REQUIRED >
<!ELEMENT months (alias | monthContext*) >
<!ELEMENT monthContext (alias | monthWidth*) >
<!ATTLIST monthContext type (format | stand-alone) #REQUIRED >
<!ELEMENT monthWidth (alias | month*) >
<!ATTLIST monthWidth type (abbreviated | narrow | wide) #REQUIRED >
<!ELEMENT month ( #PCDATA ) >
<!ATTLIST month type (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13) #REQUIRED >
<!ATTLIST month draft (approved | contributed | provisional | unconfirmed | true | false) #IMPLIED >
    <!--@METADATA-->
<!ELEMENT numbers (symbols*) >
<!ELEMENT symbols (alias | (decimal?, group?, nan?)) >
<!ATTLIST symbols numberSystem CDATA #IMPLIED >
<!ELEMENT decimal ( #PCDATA ) >
<!ATTLIST decimal draft (approved | contributed | provisional | unconfirmed | true | false) #IMPLIED >
    <!--@METADATA-->
<!ELEMENT group ( #PCDATA ) >
<!ATTLIST group draft (approved | contributed | provisional | unconfirmed | true | false) #IMPLIED >
    <!--@METADATA-->
<!ELEMENT nan ( #PCDATA ) >
<!ELEMENT units (unitLength*) >
<!ELEMENT unitLength (alias | unit*) >
<!ATTLIST unitLength type (long | short | narrow) #REQUIRED >
<!ELEMENT unit (alias | (displayName*, unitPattern*)) >
<!ATTLIST unit type NMTOKEN #REQUIRED >
<!ELEMENT displayName ( #PCDATA ) >
<!ATTLIST displayName count (0 | 1 | zero | one | two | few | many | other) #IMPLIED >
<!ELEMENT unitPattern ( #PCDATA ) >
<!ATTLIST unitPattern count (0 | 1 | zero | one | two | few | many | other) #REQUIRED >

=== Rawframe-Project/maul-locale/test/cldr/common/main/xx.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ldml SYSTEM "../../common/dtd/ldml.dtd">
<!--
SPDX-License-Identifier: MIT
Copyright (c) 2026 Sirac Ozmen
-->
<ldml>
	<identity>
		<version number="$Revision$"/>
		<language type="xx"/>
	</identity>
	<localeDisplayNames>
		<languages>
			<language type="de">Deutsch</language>
			<language type="en">English</language>
			<language type="en" menu="core">English (core)</language>
		</languages>
	</localeDisplayNames>
	<layout>
		<orientation characters="right-to-left" lines="top-to-bottom"/>
	</layout>
	<characters>
		<exemplarCharacters type="index">[A B {CH} \u0110 C D-F]</exemplarCharacters>
	</characters>
	<dates>
		<calendars>
			<calendar type="gregorian">
				<months>
					<monthContext type="format">
						<monthWidth type="wide">
							<month type="1">January</month>
							<month type="2">February</month>
						</monthWidth>
					</monthContext>
				</months>
			</calendar>
		</calendars>
	</dates>
	<numbers>
		<symbols numberSystem="latn">
			<decimal>,</decimal>
			<group>.</group>
		</symbols>
	</numbers>
	<units>
		<unitLength type="short">
			<unit type="duration-hour">
				<displayName>hr</displayName>
				<unitPattern count="one">{0} hr</unitPattern>
				<unitPattern count="other">{0} hrs</unitPattern>
			</unit>
		</unitLength>
	</units>
</ldml>

=== Rawframe-Project/maul-locale/test/cldr/common/main/xx_YY.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ldml SYSTEM "../../common/dtd/ldml.dtd">
<!--
SPDX-License-Identifier: MIT
Copyright (c) 2026 Sirac Ozmen
-->
<ldml>
	<identity>
		<version number="$Revision$"/>
		<language type="xx"/>
		<territory type="YY"/>
	</identity>
	<localeDisplayNames>
		<languages>
			<language type="en">∅∅∅</language>
		</languages>
	</localeDisplayNames>
	<dates>
		<calendars>
			<calendar type="gregorian">
				<months>
					<monthContext type="format">
						<monthWidth type="abbreviated">
							<month type="1" draft="contributed">Jan.</month>
							<month type="2" draft="provisional">Feb.</month>
						</monthWidth>
					</monthContext>
					<monthContext type="stand-alone">
						<monthWidth type="abbreviated">
							<month type="1">↑↑↑</month>
						</monthWidth>
					</monthContext>
				</months>
			</calendar>
		</calendars>
	</dates>
	<numbers>
		<symbols numberSystem="latn">
			<decimal>↑↑↑</decimal>
			<group draft="unconfirmed">'</group>
		</symbols>
	</numbers>
</ldml>

=== Rawframe-Project/maul-locale/test/cldr/common/main/root.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ldml SYSTEM "../../common/dtd/ldml.dtd">
<!--
SPDX-License-Identifier: MIT
Copyright (c) 2026 Sirac Ozmen
-->
<ldml>
	<identity>
		<version number="$Revision$"/>
		<language type="root"/>
	</identity>
	<dates>
		<calendars>
			<calendar type="buddhist">
				<months>
					<alias source="locale" path="../../calendar[@type='gregorian']/months"/>
				</months>
			</calendar>
			<calendar type="gregorian">
				<months>
					<monthContext type="format">
						<monthWidth type="abbreviated">
							<alias source="locale" path="../monthWidth[@type='wide']"/>
						</monthWidth>
						<monthWidth type="wide">
							<month type="1">M01</month>
							<month type="2">M02</month>
						</monthWidth>
					</monthContext>
					<monthContext type="stand-alone">
						<monthWidth type="abbreviated">
							<alias source="locale" path="../../monthContext[@type='format']/monthWidth[@type='abbreviated']"/>
						</monthWidth>
					</monthContext>
				</months>
			</calendar>
		</calendars>
	</dates>
	<numbers>
		<symbols numberSystem="latn">
			<decimal>.</decimal>
			<group>,</group>
			<nan>NaN</nan>
		</symbols>
	</numbers>
	<units>
		<unitLength type="narrow">
			<alias source="locale" path="../unitLength[@type='short']"/>
		</unitLength>
	</units>
</ldml>
